# Becoming AI Configuration

# Model configuration
# Local model for thought generation
local_model: "deepseek-ai/deepseek-R1-Distill-Llama-8B"
# Quantization level (int8, int4, or fp16)
quantization: "int8"
# Cache directory for downloaded models (optional)
cache_dir: "models/cache"

# Frontier model for deeper reflections and chat
frontier_model: "claude-3-7-sonnet-20250219"
# Maximum API calls per day to manage costs
max_daily_calls: 100

# Thought process configuration
# Interval between thoughts in seconds
thought_interval: 60.0

# Memory configuration
# Whether to use a remote database instead of local SQLite
use_remote_db: false
# Path to SQLite database (if using local DB)
local_db_path: "data/memories.db"
# Path for vector save/load
vector_store_path: "data/vectors.pkl"
  
# Remote database settings (only used if use_remote_db is true)
remote_db_host: "localhost"
remote_db_port: 3306
remote_db_user: "becoming_ai"
remote_db_password: ""

# Web server configuration
# Host to bind the web server
server_host: "0.0.0.0"
# Port for the web server
server_port: 5000

# Additional settings
load_chat_exports: True
chat_exports_path: "data/chat_exports.json"