# System configuration
system:
  debug: false
  frontier_only: false
  data_dir: "data"
  log_dir: "logs"

# Server configuration
server:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 5000

# Model configuration
models:
  # Local model for thought generation
  local:
    name: "deepseek-ai/deepseek-R1-Distill-Llama-8B"
    quantization: "int8"
    cache_dir: "models/cache"
  
  # Frontier model for deeper reflections and chat
  frontier:
    name: "claude-3-7-sonnet-20250219"
    max_daily_calls: 100

# Thought process configuration
thought_loop:
  interval: 60.0  # seconds
  max_length: 1000

# Memory configuration
memory:
  # Vector database configuration
  vector_db:
    type: "chroma"
    collection_name: "ai_memories"
    persist_directory: "data/memory_vectors"
  
  # Embedding configuration
  embedding:
    provider: "sentence-transformers"
    model: "sentence-transformers/all-mpnet-base-v2"
  
  # Embedding cache settings
  cache:
    directory: "data/embedding_cache"
    max_size: 10000  # Maximum in-memory cache entries
    expiry_days: 90  # How long to keep cached embeddings
  
  # Consolidation configuration
  consolidation:
    interval: 86400  # Seconds between consolidation (24 hours)
    min_cluster_size: 3  # Minimum memories to form a cluster
    similarity_threshold: 0.75  # Threshold for clustering

# Additional settings
import:
  load_chat_exports: false
  chat_exports_path: "data/chat_exports.json"