name: becoming-ai
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pytorch=2.0.0
  - cudatoolkit=11.7  # Remove if you don't have a compatible GPU
  - numpy=1.24.3
  - flask=2.3.2
  - pyyaml=6.0
  - pip:
    - transformers==4.30.2
    - sentence-transformers==2.2.2
    - anthropic=0.49.0-py3-none-any
    - pymysql==1.1.0  # Optional, only needed for remote MySQL database
    - scikit-learn==1.2.2
    - flask-cors==4.0.0
    - python-dotenv==1.0.0

    - schedule==1.2.0  # For scheduling tasks